### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by rjksn** [apertureless/vue-chartjs#193]
### Expected Behavior

I've reverted to just your example…
http://vue-chartjs.org/#/home?id=example

### Actual Behavior

I've even gone to copy the exact examples from the website (Chart) and I get these errors. 

```
[Vue warn]: Error in mounted hook: "TypeError: Cannot convert undefined or null to object"

found in

---> <LineChart>
       <DashGraph> at /…dashboard/client/views/dashGraph.vue
         <Home> at /…dashboard/client/views/Home.vue
           <Root>

vue.runtime.esm.js:562 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at mergeObject (eval at <anonymous> (client.js:3736), <anonymous>:48:12)
    at deepmerge (eval at <anonymous> (client.js:3736), <anonymous>:70:16)
    at mergeOptions (eval at <anonymous> (client.js:860), <anonymous>:15:34)
    at VueComponent.renderChart (eval at <anonymous> (client.js:4325), <anonymous>:85:52)
    at VueComponent.boundFn [as renderChart] (eval at <anonymous> (client.js:802), <anonymous>:182:14)
    at VueComponent.mounted (eval at <anonymous> (client.js:2821), <anonymous>:36:10)
    at callHook (eval at <anonymous> (client.js:802), <anonymous>:2662:21)
    at Object.insert (eval at <anonymous> (client.js:802), <anonymous>:3523:7)
    at invokeInsertHook (eval at <anonymous> (client.js:802), <anonymous>:5466:28)

```

### Environment
- vue.js version: 2.2.0 or 2.4.0 (I've done this in multiple starter packs, and updated before submitting the exact same error) 
- vue-chart.js version: 2.8.4
- npm version: 5.3.0

Wherever it's called from

```
<template>
  <div class="small">
    <line-chart :chart-data="datacollection"></line-chart>
    <button @click="fillData()">Randomize</button>
  </div>
</template>

<script>
  import LineChart from './../components/LineChart.js';

  export default {
    components: {
      LineChart
    },
    data() {
      return {
        datacollection: null
      };
    },
    mounted() {
      this.fillData();
    },
    methods: {
      fillData() {
        this.datacollection = {
          labels: [this.getRandomInt(), this.getRandomInt()],
          datasets: [
            {
              label: 'Data One',
              backgroundColor: '#f87979',
              data: [this.getRandomInt(), this.getRandomInt()]
            }, {
              label: 'Data One',
              backgroundColor: '#f87979',
              data: [this.getRandomInt(), this.getRandomInt()]
            }
          ]
        };
      },
      getRandomInt() {
        return Math.floor(Math.random() * (50 - 5 + 1)) + 5;
      }
    }
  };
</script>

<style>
  .small {
    max-width: 600px;
    margin:  150px auto;
  }
</style>

```

linechart.js 

```
import { Line, mixins } from 'vue-chartjs';
const { reactiveProp } = mixins;

export default Line.extend({
  mixins: [reactiveProp],
  props: ['options'],
  mounted() {
    // this.chartData is created in the mixin.
    // If you want to pass options please create a local options object
    this.renderChart(this.chartData, this.options);
  }
});

```

**Comment by woodjamie** [comment]
Out of interest could you trying changing back to version 2.8.3 and see if you continue to see errors? This looks very similar to what I'm experiencing in #192.

**Comment by apertureless** [comment]
This seem to be releated to `deepmerge` which works differently from lodash merge.
Will fix this asap.

**Comment by apertureless** [comment]
Fixed in `2.8.5`

**Comment by rjksn** [comment]
Thanks for the update, i'm still having issues.  

```
vue.runtime.esm.js:475 [Vue warn]: Error in mounted hook: "Error: first argument should be an array with at least two elements"

found in

---> <LineChart>
       <Home> at /Users/rjackson/Sites/dreamofalifetime/dansboard/client/views/Home.vue
         <Root>
warn @ vue.runtime.esm.js:475
handleError @ vue.runtime.esm.js:558
callHook @ vue.runtime.esm.js:2663
insert @ vue.runtime.esm.js:3522
invokeInsertHook @ vue.runtime.esm.js:5465
patch @ vue.runtime.esm.js:5635
Vue._update @ vue.runtime.esm.js:2410
updateComponent @ vue.runtime.esm.js:2534
get @ vue.runtime.esm.js:2877
Watcher @ vue.runtime.esm.js:2866
mountComponent @ vue.runtime.esm.js:2538
Vue$3.$mount @ vue.runtime.esm.js:7397
(anonymous) @ index.js:9
(anonymous) @ client.js:2773
__webpack_require__ @ client.js:660
fn @ client.js:84
(anonymous) @ client.js:4619
__webpack_require__ @ client.js:660
(anonymous) @ client.js:709
(anonymous) @ client.js:712
vue.runtime.esm.js:562 Error: first argument should be an array with at least two elements
    at Function.deepmergeAll [as all] (eval at <anonymous> (client.js:3724), <anonymous>:76:15)
    at mergeOptions (eval at <anonymous> (client.js:860), <anonymous>:15:30)
    at VueComponent.renderChart (eval at <anonymous> (client.js:4313), <anonymous>:85:52)
    at VueComponent.boundFn [as renderChart] (eval at <anonymous> (client.js:802), <anonymous>:182:14)
    at VueComponent.mounted (eval at <anonymous> (client.js:2821), <anonymous>:13:10)
    at callHook (eval at <anonymous> (client.js:802), <anonymous>:2662:21)
    at Object.insert (eval at <anonymous> (client.js:802), <anonymous>:3523:7)
    at invokeInsertHook (eval at <anonymous> (client.js:802), <anonymous>:5466:28)
    at Vue$3.patch [as __patch__] (eval at <anonymous> (client.js:802), <anonymous>:5636:5)
    at Vue$3.Vue._update (eval at <anonymous> (client.js:802), <anonymous>:2411:19)

```

I had to install the deepmerge dependency myself, so not sure if it's right.

yarn.lock
```
deepmerge@^1.5.1:
  version "1.5.1"
  resolved "https://registry.yarnpkg.com/deepmerge/-/deepmerge-1.5.1.tgz#c053bf06fd7276f1994f70c09a0760cb61a56237"
```

```
vue-chartjs@^2.8.5:
  version "2.8.5"
  resolved "https://registry.yarnpkg.com/vue-chartjs/-/vue-chartjs-2.8.5.tgz#6d0cbe8c4082c543d9f9b3b2a582d728d0b950d9"
  dependencies:
    lodash.merge "^4.6.0"
```

```
vue@^2.4.0:
  version "2.4.2"
  resolved "https://registry.yarnpkg.com/vue/-/vue-2.4.2.tgz#a9855261f191c978cc0dc1150531b8d08149b58c"
```

**Comment by apertureless** [comment]
deepmerge is removed and replaced with lodash.merge
Try to delete the `node_modules` folder and make an `npm install` or `yarn install`

**Comment by cocochepeau** [comment]
It might be related to cache issues but I tried the `2.8.5` and it appears that deepmerge is still being used in helpers. It's weird.
I also tried reinstalling node modules but still the same issue.

Rolled back to `2.8.3` for now and it works as expected.

**Comment by apertureless** [comment]
#194  

Seems that the npm publish was kind of broken. 
Please try `2.8.6`

**Comment by rjksn** [comment]
Sweet! Thanks so much! :D

**Comment by Huzefa1122** [comment]
Hey, I am not sure if this is relevant to this specific issue or i have to create new issue but here this is happening in version 4.4.7, I am using react 

![Image](https://github.com/user-attachments/assets/0ff926be-fcc3-4ea0-a504-e1fdaab19ebb)
